apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.certManagerDeployment.deployment.certImporter.persistentVolume.annotations }}
  annotations:
    {{ toYaml .Values.certManagerDeployment.deployment.certImporter.persistentVolume.annotations | indent 2 }}
  {{- end }}
  name: {{ include "cert-exporter.fullname" . }}
spec:
  storageClassName: "{{ .Values.certManagerDeployment.deployment.certImporter.persistentVolume.storageClass }}"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
