apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cert-exporter.fullname" . }}
  labels:
    {{ include "cert-exporter.certManagerDeploymentLabels" . | nindent 4 }}
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi