apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-exporter.fullname" . }}-importer
  labels:
    {{ include "cert-exporter.certManagerDeploymentLabels" . | nindent 4 }}
type: Opaque
data:
  username: {{ default "" .Values.certManagerDeployment.deployment.certImporter.credentials.username | b64enc | quote }}
  password: {{ default "" .Values.certManagerDeployment.deployment.certImporter.credentials.password | b64enc | quote }}