apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-exporter.fullname" . }}-importer
  labels:
    {{ include "cert-exporter.certManagerDeploymentLabels" . | nindent 4 }}
spec:
  type: {{ .Values.certManagerDeployment.service.type }}
  ports:
    - port: 4500
      name: http
      targetPort: 4500
  selector:
    {{ include "cert-exporter.certManagerDeploymentSelectorLabels" . | nindent 6 }}
